### ISSUE TITLE
Updating State for Performance causes:  Minified React error #185

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/CoreFPS114#12]
```
sp-pages-assembly_en-us_74e474ef41247374e69a1383c7e8a745.js:69 
        
       Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zs (sp-pages-assembly_en-us_74e474ef41247374e69a1383c7e8a745.js:69:96239)
    at Object.enqueueSetState (sp-pages-assembly_en-us_74e474ef41247374e69a1383c7e8a745.js:69:55012)
    at y.setState (sp-pages-assembly_en-us_74e474ef41247374e69a1383c7e8a745.js:3:2274)
    at oIu5.FpsCore114Banner.componentDidUpdate (FpsCore114Banner.tsx:154:12)
    at ss (sp-pages-assembly_en-us_74e474ef41247374e69a1383c7e8a745.js:69:89412)
    at bc (sp-pages-assembly_en-us_74e474ef41247374e69a1383c7e8a745.js:69:106935)
    at t.unstable_runWithPriority (sp-pages-assembly_en-us_74e474ef41247374e69a1383c7e8a745.js:69:5166)
    at Gi (sp-pages-assembly_en-us_74e474ef41247374e69a1383c7e8a745.js:69:51060)
    at hc (sp-pages-assembly_en-us_74e474ef41247374e69a1383c7e8a745.js:69:103601)
    at ac (sp-pages-assembly_en-us_74e474ef41247374e69a1383c7e8a745.js:69:99755)
```

## Console:  
![image](https://user-images.githubusercontent.com/49648086/185262576-bbae7638-ee90-4dc3-b618-2f976c0728a5.png)

## Points to this line:
![image](https://user-images.githubusercontent.com/49648086/185262618-7b1282e7-0449-48ba-8386-f5a73a721900.png)

## This is the current state:
![image](https://user-images.githubusercontent.com/49648086/185262718-44f2bf1c-1ab8-4a89-bf20-138616a3a090.png)

**Comment by mikezimm** [comment]
## This is similar component didUpdate in ALVFM that does not cause an error

![image](https://user-images.githubusercontent.com/49648086/185263011-a36dbeb1-8906-49fd-aa9a-7dc6cd519e29.png)

**Comment by mikezimm** [comment]
## Fixed this one.... human error

I was updating state on fpsconsole (red arrow) instead of refresh (green arrow).
Since fpsconsole was a constant always true, it kept cycling through setState({})

![image](https://user-images.githubusercontent.com/49648086/185263339-d7423994-06bd-4123-9cc0-a2bee10da23b.png)
